
/// @addtogroup watchstock-server
/// @{
/// @file stock_names.js
/// @brief: 
///
/// Author: Pedro Palomo Perez
/// Mail: pedro.palomoperez@gmail.com
/// Github: pedropalomo
/// Revision: 1.0


const stocks_list = [

{ code: "FOXA", name: "21ST CENTRY FOX A CM"},
{ code: "FOX", name: "21ST CENTRY FOX B CM"},
{ code: "ATVI", name: "ACTIVISION BLIZZARD"},
{ code: "ADBE", name: "ADOBE SYSTEMS INC"},
{ code: "AKAM", name: "AKAMAI TECHNOLOGIES"},
{ code: "ALXN", name: "ALEXION PHARM INC"},
{ code: "GOOGL", name: "ALPHABET CL A CMN"},
{ code: "GOOG", name: "ALPHABET CL C CAP"},
{ code: "AMZN", name: "AMAZON.COM INC"},
{ code: "AAL", name: "AMERICAN AIRLINES GP"},
{ code: "AMGN", name: "AMGEN"},
{ code: "ADI", name: "ANALOG DEVICES CMN"},
{ code: "AAPL", name: "APPLE INC."},
{ code: "AMAT", name: "APPLIED MATERIALS"},
{ code: "ADSK", name: "AUTODESK INC"},
{ code: "ADP", name: "AUTOMATIC DATA PROCS"},
{ code: "AVGO", name: "AVAGO TECHNOLOGIES L"},
{ code: "BIDU", name: "BAIDU INC."},
{ code: "BBBY", name: "BED BATH BEYOND"},
{ code: "BIIB", name: "BIOGEN INC CMN"},
{ code: "BMRN", name: "BIOMARIN PHARMACEUT"},
{ code: "BRCM", name: "BROADCOM CORP"},
{ code: "CHRW", name: "C.H. ROBINSON WW"},
{ code: "CA", name: "CA INC"},
{ code: "CELG", name: "CELGENE CORP"},
{ code: "CERN", name: "CERNER CORP"},
{ code: "CHTR", name: "CHARTER COMMUNICATIO"},
{ code: "CHKP", name: "CHECK POINT SOFTWARE"},
{ code: "CSCO", name: "CISCO SYSTEMS INC"},
{ code: "CTXS", name: "CITRIX SYSTEMS INC"},
{ code: "CTSH", name: "COGNIZANT TECH SOL"},
{ code: "CMCSK", name: "COMCAST CL A SPCL"},
{ code: "CMCSA", name: "COMCAST CORP A"},
{ code: "COST", name: "COSTCO WHOLESALE"},
{ code: "DISCA", name: "DISCOVERY COMM A"},
{ code: "DISCK", name: "DISCOVERY COMM INC"},
{ code: "DISH", name: "DISH NETWORK CORP"},
{ code: "DLTR", name: "DOLLAR TREE INC"},
{ code: "EBAY", name: "EBAY INC."},
{ code: "EA", name: "ELECTRONIC ARTS INC"},
{ code: "EXPD", name: "EXPEDITORS INTL"},
{ code: "ESRX", name: "EXPRESS SCRIPTS"},
{ code: "FB", name: "FACEBOOK INC"},
{ code: "FAST", name: "FASTENAL CO"},
{ code: "FISV", name: "FISERV INC."},
{ code: "GRMN", name: "GARMIN LTD"},
{ code: "GILD", name: "GILEAD SCIENCES INC"},
{ code: "HSIC", name: "HENRY SCHEIN INC."},
{ code: "ILMN", name: "ILLUMINA INC."},
{ code: "INCY", name: "INCYTE CORPORATION"},
{ code: "INTC", name: "INTEL CORP"},
{ code: "INTU", name: "INTUIT INC"},
{ code: "ISRG", name: "INTUITIVE SURG INC."},
{ code: "JD", name: "JD.COM INC. ADS"},
{ code: "KLAC", name: "K L A-TENCOR CORP"},
{ code: "GMCR", name: "KEURIG GREEN MTN CMN"},
{ code: "KHC", name: "KRAFT HEINZ CO CMN"},
{ code: "LRCX", name: "LAM RESEARCH CORP"},
{ code: "LBTYA", name: "LIBERTY GLOBAL ORD A"},
{ code: "LBTYK", name: "LIBERTY GLOBAL ORD C"},
{ code: "QVCA", name: "LIBERTY INT QVC SR A"},
{ code: "LILA", name: "LIBERTY LILAC CL A"},
{ code: "LILAK", name: "LIBERTY LILAC CL C"},
{ code: "LMCK", name: "LIBERTY MEDIA C"},
{ code: "LMCA", name: "LIBERTY MEDIA SRS A"},
{ code: "LVNTA", name: "LIBERTY VNTRS SRS A"},
{ code: "LLTC", name: "LINEAR TECHNOLOGY"},
{ code: "MAR", name: "MARRIOT INT CL A"},
{ code: "MAT", name: "MATTEL INC"},
{ code: "MU", name: "MICRON TECHNOLOGY"},
{ code: "MSFT", name: "MICROSOFT CORP"},
{ code: "MDLZ", name: "MONDELEZ INTL CMN A"},
{ code: "MNST", name: "MONSTER BEVERAGE CP"},
{ code: "MYL", name: "MYLAN NV ORD SHS"},
{ code: "NTAP", name: "NETAPP INC."},
{ code: "NFLX", name: "NETFLIX INC."},
{ code: "NVDA", name: "NVIDIA CORPORATION"},
{ code: "NXPI", name: "NXP SEMICONDUCTORS"},
{ code: "ORLY", name: "O'REILLY AUTOMOTIVE"},
{ code: "PCAR", name: "PACCAR INC."},
{ code: "PAYX", name: "PAYCHEX INC."},
{ code: "QCOM", name: "QUALCOMM INC"},
{ code: "REGN", name: "REGENERON PHARMACEUT"},
{ code: "ROST", name: "ROSS STORES INC."},
{ code: "SNDK", name: "SANDISK CORPORATION"},
{ code: "SBAC", name: "SBA COMMUNICATIONS"},
{ code: "STX", name: "SEAGATE TECHNOLOGY"},
{ code: "SIRI", name: "SIRIUS XM HOLDINGS I"},
{ code: "SWKS", name: "SKYWORKS SOLUTIONS"},
{ code: "SPLS", name: "STAPLES INC."},
{ code: "SBUX", name: "STARBUCKS CORP"},
{ code: "SRCL", name: "STERICYCLE INC."},
{ code: "SYMC", name: "SYMANTEC CORPORATION"},
{ code: "TSLA", name: "TESLA MOTORS INC"},
{ code: "TXN", name: "TEXAS INSTRUMENTS"},
{ code: "PCLN", name: "THE PRICELINE GP CM"},
{ code: "TSCO", name: "TRACTOR SUPPLY CO"},
{ code: "TRIP", name: "TRIPADVISOR INC."},
{ code: "VRSK", name: "VERISK ANALYTICS INC"},
{ code: "VRTX", name: "VERTEX PHARMACEUTIC"},
{ code: "VIAB", name: "VIACOM INC CL B"},
{ code: "VIP", name: "VIMPELCOM LTD"},
{ code: "VOD", name: "VODAFONE GRP PLC ADS"},
{ code: "WBA", name: "WALGREENS BTS ALN CM"},
{ code: "WDC", name: "WESTERN DIGITAL CP"},
{ code: "WFM", name: "WHOLE FOODS MARKET"},
{ code: "WYNN", name: "WYNN RESORTS LIMITED"},
{ code: "XLNX", name: "XILINX INC."},
{ code: "YHOO", name: "YAHOO! INC."}];

exports.stocks_list = stocks_list;

/// @}